//
//	THIS SOFTWARE AND ANY ACCOMPANYING DOCUMENTATION IS RELEASED "AS IS." THE
//	U.S.GOVERNMENT MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, CONCERNING
//	THIS SOFTWARE AND ANY ACCOMPANYING DOCUMENTATION, INCLUDING, WITHOUT LIMITATION,
//	ANY WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT
//	WILL THE U.S. GOVERNMENT BE LIABLE FOR ANY DAMAGES, INCLUDING ANY LOST PROFITS,
//	LOST SAVINGS OR OTHER INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE,
//	OR INABILITY TO USE, THIS SOFTWARE OR ANY ACCOMPANYING DOCUMENTATION, EVEN IF
//	INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.
//
//
// DebugDefine.h: .
//
//////////////////////////////////////////////////////////////////////

#if !defined(DEBUG_DEFINE_H__INCLUDED_)
#define DEBUG_DEFINE_H__INCLUDED_


#define DEBUG_TIME_START (21.0)
//#define DEBUG(time) if(time>DEBUG_TIME_START){mexPrintf("%s:%d\n",__FILE__,__LINE__);}
#define DEBUG(time)
#include "mex.h"


#endif	//DEBUG_DEFINE_H__INCLUDED_