%%
%%	THIS SOFTWARE AND ANY ACCOMPANYING DOCUMENTATION IS RELEASED "AS IS." THE
%%	U.S.GOVERNMENT MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, CONCERNING
%%	THIS SOFTWARE AND ANY ACCOMPANYING DOCUMENTATION, INCLUDING, WITHOUT LIMITATION,
%%	ANY WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT
%%	WILL THE U.S. GOVERNMENT BE LIABLE FOR ANY DAMAGES, INCLUDING ANY LOST PROFITS,
%%	LOST SAVINGS OR OTHER INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE,
%%	OR INABILITY TO USE, THIS SOFTWARE OR ANY ACCOMPANYING DOCUMENTATION, EVEN IF
%%	INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.
%%

global MaxNumberVehicles;
global MaxNumberTargets;
global MaxNumberTasks;
global g_MaxBenefit;

MaxNumberVehicles = 3
MaxNumberTargets = 3
MaxNumberTasks = 3
g_MaxBenefit = 1.0e+07

% setup path info
tdir = ['..', filesep, '..', filesep, '..', filesep];
mdir = [tdir, 'm-file'];

addpath(mdir);
addpath(GetLibDir(tdir));
