//
//	THIS SOFTWARE AND ANY ACCOMPANYING DOCUMENTATION IS RELEASED "AS IS." THE
//	U.S.GOVERNMENT MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, CONCERNING
//	THIS SOFTWARE AND ANY ACCOMPANYING DOCUMENTATION, INCLUDING, WITHOUT LIMITATION,
//	ANY WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT
//	WILL THE U.S. GOVERNMENT BE LIABLE FOR ANY DAMAGES, INCLUDING ANY LOST PROFITS,
//	LOST SAVINGS OR OTHER INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE,
//	OR INABILITY TO USE, THIS SOFTWARE OR ANY ACCOMPANYING DOCUMENTATION, EVEN IF
//	INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.
//
//
// SSDebugDefine.h: .
//
//////////////////////////////////////////////////////////////////////

#if !defined(SSDEBUG_DEFINE_H__INCLUDED_)
#define SSDEBUG_DEFINE_H__INCLUDED_

// prevent redefinition of system DEBUG macro; previous DEBUG -> DEBUG_TIME
#ifdef SSDEBUG
# define SSDEBUG_TIME(time) if(time>130.0){mexPrintf("%s:%d@t=%g sec\n",__FILE__,__LINE__,time);}
#else
# define SSDEBUG_TIME(time)
#endif

#endif	//SSDEBUG_DEFINE_H__INCLUDED_
